//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.10 at 11:04:46 PM CET 
//


package com.neotec.todo.controler;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

import org.joda.time.DateTime;
import org.joda.time.Duration;




import com.neotec.todo.ToDo;


/**
 * <p>Java class for Task complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Task">
 *   &lt;complexContent>
 *     &lt;restriction base="xsd:anyType">
 *       &lt;sequence>
 *         &lt;element name="Id" type="xsd:long"/>
 *         &lt;element name="Name" type="xsd:string"/>
 *         &lt;element name="Description" type="xsd:string" minOccurs="0"/>
 *         &lt;element name="Note" type="xsd:string" minOccurs="0"/>
 *         &lt;element name="Priority" type="{com.neotec.todo}PriorityType" minOccurs="0"/>
 *         &lt;element name="Category" type="xsd:string"/>
 *         &lt;element name="Project" type="{com.neotec.todo}ProjectType"/>
 *         &lt;element name="State" type="{com.neotec.todo}StateType"/>
 *         &lt;element name="Resources" type="xsd:string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="EstimatedTime" type="xsd:duration" minOccurs="0"/>
 *         &lt;element name="DueDateTime" type="xsd:dateTime" minOccurs="0"/>
 *         &lt;element name="BeginningDateTime" type="xsd:dateTime" minOccurs="0"/>
 *         &lt;element name="EndDateTime" type="xsd:dateTime" minOccurs="0"/>
 *         &lt;element name="Prerequisite" type="{com.neotec.todo}Task" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" type="xsd:integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Task", propOrder = {
    "id",
    "name",
    "description",
    "note",
    "priority",
    "category",
    "project",
    "state",
    "resources",
    "estimatedTime",
    "dueDateTime",
    "beginningDateTime",
    "endDateTime",
    "prerequisite"
})
public class Task {
	static	String	version;
    protected int id;								//automatic
    protected String name;							//required
    protected String description;					//optionnal
    protected String note;							//optionnal
    protected Integer priority;						//optionnal
    protected String category;						//optionnal
    protected Integer project;						//coditionnal
    protected StateType stateType;					//required (automatic)
    protected List<String> resources;				//optionnal
    protected Duration estimatedTime;				//optionnal
    protected DateTime dueDateTime;					//opionnal
    protected DateTime beginningDateTime;			//automatic
    protected DateTime endDateTime;				//automatic
    protected List<Task> prerequisite;				//optionnal


    
    public Task(){
    	super();

    	
    	version=ToDo.version;
    	id= 0;								// automatic
    	name="";							// required
    	description="";						// optionnal
    	note="";							// optionnal
    	priority=0;							// optionnal
    	category=null;						// optionnal
    	project=null;						// conditionnal
    	stateType=StateType.NOT_STARTED;	// required(automatic)
    	resources=null;						// optionnal
    	estimatedTime=new Duration(0);		// optionnal
    	dueDateTime=new DateTime(0);		// optionnal
    	beginningDateTime=null;				// optionnal automatic
    	endDateTime=null;					// optionnal automatic
    	prerequisite=null;					// optionnal
    	
    }
    public DateTime getDueBeginningDateTime() {
    	
    	if(dueDateTime.getMillis() == 0) 
    		return (new DateTime(0));
    	else
    		return dueDateTime.minus(estimatedTime);
	}
	/**
     * Gets the value of the id property.
     * 
     */    
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPriority(Integer value) {
        this.priority = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategory(String value) {
        this.category = value;
    }

    /**
     * Gets the value of the project property.
     * 
     * @return
     *     possible object is
     *     {@link Project }
     *     
     */
    public Integer getProject() {
        return project;
    }

    /**
     * Sets the value of the project property.
     * 
     * @param integer
     *     allowed object is
     *     {@link Project }
     *     
     */
    public void setProject(Integer integer) {
        this.project = integer;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link StateType }
     *     
     */
    public StateType getState() {
        return stateType;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link StateType }
     *     
     */
    public void setState(StateType value) {
        this.stateType = value;
    }

    /**
     * Gets the value of the resources property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resources property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResources().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getResources() {
           return this.resources;
    }

    /**
     * Gets the value of the estimatedTime property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getEstimatedTime() {
        return estimatedTime;
    }

    /**
     * Sets the value of the estimatedTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setEstimatedTime(Duration value) {
        this.estimatedTime = value;
    }
      /**
     * Gets the value of the dueDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link DateTime }
     *     
     */
    public DateTime getDueDateTime() {
        return dueDateTime;
    }

    /**
     * Sets the value of the dueDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTime }
     *     
     */
    public void setDueDateTime(DateTime value) {
        this.dueDateTime = value;
    }

    /**
     * Gets the value of the beginningDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link DateTime }
     *     
     */
    public DateTime getBeginningDateTime() {
        return beginningDateTime;
    }

    /**
     * Sets the value of the beginningDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTime }
     *     
     */
    public void setBeginningDateTime(DateTime value) {
        this.beginningDateTime = value;
    }

    /**
     * Gets the value of the endDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link DateTime }
     *     
     */
    public DateTime getEndDateTime() {
        return endDateTime;
    }

    /**
     * Sets the value of the endDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTime }
     *     
     */
    public void setEndDateTime(DateTime value) {
        this.endDateTime = value;
    }
    public List<Task> getPrerequisite() {
        return this.prerequisite;
    }
    
    public void setPrerequisite(List<Task> prerequisite) {
		this.prerequisite = prerequisite;
	}
	public void setResources(List<String> resources) {
		this.resources = resources;
	}
    /**
     * Gets the value of the prerequisite property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the prerequisite property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPrerequisite().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Task }
     * 
     * 
     */
    
	public String toString(){
    	StringBuilder result=new StringBuilder();
    	result.append("Task:\n");
    	result.append("Id="+((Integer)this.getId()).toString()+"\n");
    	result.append("Name="+this.getName() + "\n");
    	result.append("Description="+this.getDescription() + "\n");
    	result.append("Note="+this.getNote() + "\n");
    	result.append("Priority="+this.getPriority().toString()+"\n");
    	result.append("Category="+this.getCategory()+"\n");
    	if(this.getProject() != null) this.getProject().toString();
    	result.append("State="+this.getState().toString()+"\n");
    	if(this.getResources() != null)result.append("Resources="+this.getResources().toString()+"\n");
    	if(this.getEstimatedTime() != null) result.append("EtimatedTime="+this.getEstimatedTime().toString()+"\n");
    	if(this.getDueDateTime() != null) result.append("DueDateTime="+this.getDueDateTime().toString()+"\n");
    	if(this.getDueBeginningDateTime() != null) result.append("BeginningDueDateTime="+this.getDueBeginningDateTime().toString()+"\n");
    	if(this.getBeginningDateTime() != null) result.append("BeginningDateTime="+this.getBeginningDateTime().toString()+"\n");
    	if(this.endDateTime != null) result.append("EndDateTime="+this.getEndDateTime().toString()+"\n");
    	if(this.prerequisite != null) result.append("with prerequisite\n");
    	
    	return result.toString();
    	
    }
	
	public boolean equals(Task t1){
		
		if(!t1.name.equals(this.name)) return false;
		if(!t1.description.equals(this.description)) return false;
		if(! t1.note.equals(this.note)) return false;
		if(t1.priority != this.priority) return false;
		if(t1.category==null){return this.category==null;}
		else
			if(!t1.category.equals(this.category)) return false;
		if(t1.project!=this.project) return false;
		if(t1.stateType!=this.stateType) return false;
//		if(t1.resources!=this.resources) return false;
		if(t1.estimatedTime==null){ return this.estimatedTime==null;}
		else 
			if(! t1.estimatedTime.equals(this.estimatedTime)) {return false;}
		if(t1.dueDateTime==null){ return this.dueDateTime==null;}
		else
			if(! t1.dueDateTime.equals(this.dueDateTime)) {return false;}
		if(t1.beginningDateTime==null){ return this.beginningDateTime==null;}
		else
			if(! t1.beginningDateTime.equals(this.beginningDateTime)) {return false;}
		if(t1.endDateTime==null){ return this.endDateTime==null;}
		else
			if(! t1.endDateTime.equals(this.endDateTime)) {return false;}
//		if(t1.prerequisite!=this.prerequisite) return false;
		
		return true;
	}
 	

}
    

